apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.name }}-leader-election
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.name }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.name }}-service-account
  namespace: {{ .Release.Namespace | quote }}
