apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.type }}Binding
metadata:
  name: {{ .Values.rbac.name }}-binding
  {{- if eq .Values.rbac.type "Role"  }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.type }}
  name: {{ .Values.rbac.name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.name }}-service-account
    namespace: {{ .Release.Namespace | quote }}
